development: &default
  adapter: postgresql
  database: leather-homepage_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: leather-homepage_test

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: leather-homepage_production
  pool: 5
  username: leather-homepage
  password: <%= ENV['DB_PASS'] %>
